// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/holidays": {
            "get": {
                "description": "GetHolidays",
                "summary": "GetHolidays",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "description",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "disabled",
                        "name": "disabled",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "code for relation",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "country for relation",
                        "name": "country",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "date specific holiday",
                        "name": "date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "year",
                        "name": "year",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 25,
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.Response-array_gitlab_global_ingenico_com_finops_nextgen_apps_admin_holiday_git_pkg_models_Holiday"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    }
                }
            },
            "post": {
                "description": "AddHoliday",
                "summary": "AddHoliday",
                "parameters": [
                    {
                        "description": "Holiday",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gitlab_global_ingenico_com_finops_nextgen_apps_admin_holiday_git_pkg_models.Holiday"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.Response-string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/holidays-bulk": {
            "post": {
                "description": "AddHolidayBulk",
                "summary": "AddHolidayBulk",
                "parameters": [
                    {
                        "description": "Holiday",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/gitlab_global_ingenico_com_finops_nextgen_apps_admin_holiday_git_pkg_models.Holiday"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.Response-array_string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/holidays/{id}": {
            "get": {
                "description": "GetHoliday",
                "summary": "GetHoliday",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Holiday ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.Response-gitlab_global_ingenico_com_finops_nextgen_apps_admin_holiday_git_pkg_models_Holiday"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    }
                }
            },
            "delete": {
                "description": "RemoveHoliday",
                "summary": "RemoveHoliday",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Holiday ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/relations": {
            "get": {
                "description": "GetRelations",
                "summary": "GetRelations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "code for relation",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "country for relation",
                        "name": "country",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 25,
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.Response-array_gitlab_global_ingenico_com_finops_nextgen_apps_admin_holiday_git_pkg_models_Relation"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    }
                }
            },
            "post": {
                "description": "AddRelation",
                "summary": "AddRelation",
                "parameters": [
                    {
                        "description": "Relation",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gitlab_global_ingenico_com_finops_nextgen_apps_admin_holiday_git_pkg_models.Relation"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.Response-string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/relations-bulk": {
            "post": {
                "description": "AddRelationBulk",
                "summary": "AddRelationBulk",
                "parameters": [
                    {
                        "description": "Relation",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/gitlab_global_ingenico_com_finops_nextgen_apps_admin_holiday_git_pkg_models.Relation"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.Response-array_string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/relations/{id}": {
            "get": {
                "description": "GetRelation",
                "summary": "GetRelation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Holiday ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.Response-gitlab_global_ingenico_com_finops_nextgen_apps_admin_holiday_git_pkg_models_Relation"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    }
                }
            },
            "delete": {
                "description": "RemoveRelation",
                "summary": "RemoveRelation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Holiday ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/workday": {
            "get": {
                "description": "WorkDay",
                "summary": "WorkDay",
                "parameters": [
                    {
                        "type": "string",
                        "description": "date",
                        "name": "date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "country",
                        "name": "country",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "code for relation",
                        "name": "code",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.Response-string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseMessage"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gitlab_global_ingenico_com_finops_nextgen_apps_admin_holiday_git_pkg_models.Holiday": {
            "type": "object",
            "properties": {
                "date_from": {
                    "type": "string"
                },
                "date_to": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "disabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                },
                "years": {
                    "type": "string"
                }
            }
        },
        "gitlab_global_ingenico_com_finops_nextgen_apps_admin_holiday_git_pkg_models.Relation": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "country": {
                    "type": "string"
                },
                "holiday_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "rest.Message": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "rest.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "description": "Limit is the limit used within the request.\nIf not defined in the query parameters, this should be the default value used in the service endpoint.",
                    "type": "integer"
                },
                "offset": {
                    "description": "Offset is the offset used within the request.",
                    "type": "integer"
                },
                "total_item_count": {
                    "description": "TotalItemCount is the total number of entities that match the query.",
                    "type": "integer"
                }
            }
        },
        "rest.Response-array_gitlab_global_ingenico_com_finops_nextgen_apps_admin_holiday_git_pkg_models_Holiday": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/rest.Message"
                },
                "meta": {
                    "$ref": "#/definitions/rest.Meta"
                },
                "payload": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gitlab_global_ingenico_com_finops_nextgen_apps_admin_holiday_git_pkg_models.Holiday"
                    }
                }
            }
        },
        "rest.Response-array_gitlab_global_ingenico_com_finops_nextgen_apps_admin_holiday_git_pkg_models_Relation": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/rest.Message"
                },
                "meta": {
                    "$ref": "#/definitions/rest.Meta"
                },
                "payload": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gitlab_global_ingenico_com_finops_nextgen_apps_admin_holiday_git_pkg_models.Relation"
                    }
                }
            }
        },
        "rest.Response-array_string": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/rest.Message"
                },
                "meta": {
                    "$ref": "#/definitions/rest.Meta"
                },
                "payload": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "rest.Response-gitlab_global_ingenico_com_finops_nextgen_apps_admin_holiday_git_pkg_models_Holiday": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/rest.Message"
                },
                "meta": {
                    "$ref": "#/definitions/rest.Meta"
                },
                "payload": {
                    "$ref": "#/definitions/gitlab_global_ingenico_com_finops_nextgen_apps_admin_holiday_git_pkg_models.Holiday"
                }
            }
        },
        "rest.Response-gitlab_global_ingenico_com_finops_nextgen_apps_admin_holiday_git_pkg_models_Relation": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/rest.Message"
                },
                "meta": {
                    "$ref": "#/definitions/rest.Meta"
                },
                "payload": {
                    "$ref": "#/definitions/gitlab_global_ingenico_com_finops_nextgen_apps_admin_holiday_git_pkg_models.Relation"
                }
            }
        },
        "rest.Response-string": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/rest.Message"
                },
                "meta": {
                    "$ref": "#/definitions/rest.Meta"
                },
                "payload": {
                    "type": "string"
                }
            }
        },
        "rest.ResponseMessage": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/rest.Message"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/holiday/v1",
	Schemes:          []string{},
	Title:            "holiday API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
